### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by fatklass** [Tinkoff/invest-python#100]
### Описание

Документацию бы, названия методов координально отличаются от официальных из документации https://tinkoff.github.io/investAPI/operations/
Вместо разработки занимаешься ковырянием и поиском правильных названий.

Судя по неймингу get_portfolio, вы хотели слова разделить нижними подчеркиваниями но где то что то пошло не так.. 

Как например получить GetWithdrawLimits?
Такого названия нет  client.operations.get_with_draw_limits(account_id=ACCOUNT_ID) как вы его назвали, как нам вообще догадаться?

### Желаемое решение
Потратьте пожалуйста пару часов времени сделайте хотя бы не документацию а список с сопоставленными названиями из оф документации с sdk

GetAccounts = get_accounts()
GetInfo = get_info()
GetPortfolio = get_portfolio(arg)
GetPositions = get_positions(arg)
...
GetWithdrawLimits = ????
_No response_

**Comment by andrey-vrn** [comment]
```
with Client(TOKEN) as client:
    withdraw_response = client.operations.get_withdraw_limits(account_id=ACCOUNT_ID)
```

**Comment by andrey-vrn** [comment]
При использовании IDE, например, pyCharm, список методов выводится, не надо ковырять исходники, а состав методов соответствует описанию OpenAPI.

**Comment by daxartio** [comment]
Добавим доку, чтобы было понятно как сопоставлять методы из протофайлов с питон кодом
