### ISSUE TITLE
[Feature] Определить для класса Quotation методы сравнений, сложения и вычитания

### ISSUE THREAD

**Issue by T850** [Tinkoff/invest-python#103]
### Описание

Возникает много ситуаций, когда необходимо выполнить некоторые операции с котировками, а именно сложение, вычитание двух котировок или их сравнение между собой, конвертация во float для построения индикаторов.

Вот несколько примеров, где это может понадобиться, но думаю это далеко не полный список возможных сценариев использования:
- Построение собственных свечей, например, на базе числа тиков, проторгованного объема, проторгованных рублей/долларов (к примеру, цена бумаги была 50 руб за акцию, потом цена выросла до 100 руб, объем один и тот же, но для покупки требуется сумма в 2 раза больше)..
- Вычисление цены тейк профита и стоп лосса при известной цене открытия позиции.
- Проверка не выходят ли защитные ордера за пределы верхней или нижней планки.

### Желаемое решение

Предлагаю для класса Quotation определить методы сравнений __lt__, __le__, __gt__, __ge__, __eq__, __ne__, методы сложения и вычитания __add__, __sub__, а так же метод конвертации во float. 

### Дополнительно
Реализация методов __add__, __sub__ будет зависеть от того, предполагается ли, что котировки могут иметь отрицательное значение, на бирже такие кейсы есть, к примеру, когда цена экспирации фьючерсного контракта по нефти на moex была отрицательной, так же отрицательную цену имеют многие календарные спреды, поэтому выглядит как вполне оправданный сценарий. Но возникает вопрос как тогда будет выглядеть отрицательная котировка, к примеру,  если цена равна -0.1 или -2.5: Quotation(units=0, nano=-100000000) и Quotation(units=-2, nano=-500000000) соответственно, или предполагается нечто другое? Если мое предположение про поддержку отрицательного значения котировки и как это отображать верны, то как варинт, может быть подобная реализация, через использование класса decimal.
```python
from decimal import Decimal, Context

def quotation_to_decimal(quote: "Quotation") -> Decimal:
    quote_sign = "-" if quote.units < 0 or quote.nano < 0 else ""
    quote_units, quote_nano = map(
        lambda x: str(x).replace("-", ""), (quote.units, quote.nano)
    )
    return Decimal(
        f"{quote_sign}{quote_units}.{quote_nano.rjust(9, '0')}",
        Context(prec=9),
    )


def decimal_to_quotation(number: Decimal) -> "Quotation":
    number = str(number)
    is_positive = True if not "-" in number else False
    units, nano = sum_.split(".")
    nano = nano.lstrip("0")

    if is_positive:
        return Quotation(units=units, nano=nano)
    if units[1:] == "0":
        return Quotation(units=units[1:], nano=f"-{nano}")
    return Quotation(units=units, nano=f"-{nano}")


@dataclass(eq=False, repr=True)
class Quotation(_grpc_helpers.Message):
    units: int = _grpc_helpers.int64_field(1)
    nano: int = _grpc_helpers.int32_field(2)

    def __add__(self, other: "Quotation") -> "Quotation":
        first_num = quotation_to_decimal(self)
        second_num = quotation_to_decimal(other)
        sum_ = first_num + second_num
        return decimal_to_quotation(sum_)

    def __sub__(self, other: "Quotation") -> "Quotation":
        first_num = quotation_to_decimal(self)
        second_num = quotation_to_decimal(other)
        diff = first_num - second_num
        return decimal_to_quotation(diff)

    def __eq__(self, other: "Quotation") -> bool:
        if self.units == other.units and self.nano == other.nano:
            return True
        return False

    def __lt__(self, other: "Quotation") -> bool:
        if self.units < other.units:
            return True
        if self.units == other.units and self.nano < other.nano:
            return True
        return False

    def __le__(self, other: "Quotation") -> bool:
        if self.units < other.units:
            return True
        if self.units == other.units and (
            self.nano < other.nano or self.nano == other.nano
        ):
            return True
        return False

    def __gt__(self, other: "Quotation") -> bool:
        if self.units > other.units:
            return True
        if self.units == other.units and self.nano > other.nano:
            return True
        return False

    def __ge__(self, other: "Quotation") -> bool:
        if self.units > other.units:
            return True
        if self.units == other.units and (
            self.nano > other.nano or self.nano == other.nano
        ):
            return True
        return False

    def to_float(self) -> float:
        quote_sign = "-" if self.units < 0 or self.nano < 0 else ""
        quote_units, quote_nano = map(
            lambda x: str(x).replace("-", ""), (self.units, self.nano)
        )
        quote_float = float(f"{quote_sign}{quote_units}.{quote_nano.rjust(9, '0')}")
        return round(quote_float, 9 - len(quote_nano) + len(quote_nano.rstrip("0")))

```

**Comment by T850** [comment]
Пока писал код возник вопрос, а чем изначально был мотивирован такой вариант представления цены, это способ уйти от неточности чисел с плавающей точкой или что то другое?

**Comment by irusland** [comment]
Понадобятся ли еще нативные для Quotation операции умножения, деления, возведения в степень, взятие логарифма?

**Comment by T850** [comment]
Спасибо что спросили, думаю действительно есть смысл еще добавить операции умножения и деления. Операция умножения точно будет востребована, к примеру, чтобы рассчитать значение комиссии или цену стопа, если она рассчитывается в процентах от текущей цены. Опрерация деления может применяться, к примеру, если торговая система реагирует на процентное изменение цены относительно открытия дня. Безусловно будут кейсы и с другими операциями, но думаю они редки и всех их не учесть, если уж возникнет такая необходимость всегда можно конвертировать Quotation во float, и воспользоваться операциями из других библиотек, поэтому операций сравнения, сложения, вычитания, умножения, деления и конвертации во float думаю дожно быть достатосно.
