### ISSUE TITLE
дублирование свечей при запросе истории

### ISSUE THREAD

**Issue by RuslanKosarev** [Tinkoff/invest-python#104]
### Что случилось?

В некоторых случаях при запросе истории котировок возникает дублирование свечей, например, для запроса при параметрах

figi = BBG005HLSZ23 (FXUS)
end = pd.Timestamp.utcnow()
start = end - pd.offsets.DateOffset(years=3)

name = "tinkoff-investments"
version = "0.2.0b33"

в примере нужно добавить print(df.index[df.index.duplicated()]

https://github.com/RuslanKosarev/tinkoff-invest-examples/blob/main/examples/candles.py

### Tinkoff Invest Version

0.2.0-beta33

### Python Version

3.10

### OS

Linux

### Логи

```shell
open   high    low  close   volume  is_complete
time                                                                       
2020-08-17 07:00:00+00:00  45.15  45.29  44.59  45.25   902800         True
2020-08-18 07:00:00+00:00  45.27  45.35  44.96  45.07   797500         True
2020-08-19 07:00:00+00:00  45.03  45.50  45.03  45.26   684600         True
2020-08-19 07:00:00+00:00  45.03  45.50  45.03  45.26   684600         True
2020-08-20 07:00:00+00:00  45.10  45.64  44.81  45.59   632900         True
```

**Comment by irusland** [comment]
Добавьте пожалуйста код позволяющий воспроизвести проблему

**Comment by RuslanKosarev** [comment]
https://github.com/RuslanKosarev/tinkoff-invest-examples/blob/main/examples/candles.py

**Comment by RuslanKosarev** [comment]
> Добавьте пожалуйста код позволяющий воспроизвести проблему

https://github.com/RuslanKosarev/tinkoff-invest-examples/blob/main/examples/candles.py
