### ISSUE TITLE
get_last_prices не принимает параметр

### ISSUE THREAD

**Issue by andrey-vrn** [Tinkoff/invest-python#107]
### Что случилось?

Хочу получить последние цены по списку инструментов. Получаю ошибку. 
Без параметров - все выполняется и возвращает последние цены ПО ВСЕМ инструментам.
В документации указано, что в качестве параметра может выступать список инструментов для получения последних цен.

### Воспроизведение

```
from constants import TOKEN
from tinkoff.invest import Client

with Client(TOKEN) as client:
    _list = list()
    _list.append('BBG006L8G4H1')
    response = client.market_data.get_last_prices(_list)
    print(str(response))
```

### Tinkoff Invest Version

0.2.0-beta33

### Python Version

3.10

### OS

Windows

**Comment by irusland** [comment]
```python3
from constants import TOKEN
from tinkoff.invest import Client

with Client(TOKEN) as client:
    _list = list()
    _list.append('BBG006L8G4H1')
    response = client.market_data.get_last_prices(figi=_list)
    print(str(response))
```
`*` обязывает передавать именованные аргументы
