### ISSUE TITLE
[Bug] по figi BBG000QFH687 (ТГК-1) возвращает средний прайс 0,01. Реальная цена 0,00873 (average_position_price)

### ISSUE THREAD

**Issue by HappyManRus** [Tinkoff/invest-python#112]
### Что случилось?

по figi BBG000QFH687 (ТГК-1) возвращает средний прайс 0,01 в average_position_price. Реальная цена 0,00873.
Получаю по методу get_portfolio

average_position_price: MoneyValue(currency='rub', units=0, nano=10000000)
average_position_price_fifo: MoneyValue(currency='rub', units=0, nano=8012000)
average_position_price_pt: Quotation(units=0, nano=0)
blocked: False
current_nkd: MoneyValue(currency='rub', units=0, nano=0)
current_price: MoneyValue(currency='rub', units=0, nano=8712000)
expected_yield: Quotation(units=70, nano=0)

### Воспроизведение

```python
Portfolio_data = client.operations.get_portfolio(account_id=account_id)
```

### Tinkoff Invest Version

0.2.0-beta33

### Python Version

3.10

### OS

Windows

### Логи

```shell
average_position_price: MoneyValue(currency='rub', units=0, nano=10000000)
average_position_price_fifo: MoneyValue(currency='rub', units=0, nano=8012000)
average_position_price_pt: Quotation(units=0, nano=0)
blocked: False
current_nkd: MoneyValue(currency='rub', units=0, nano=0)
current_price: MoneyValue(currency='rub', units=0, nano=8712000)
expected_yield: Quotation(units=70, nano=0)
```

**Comment by daxartio** [comment]
Это в основной репозиторий API
