### ISSUE TITLE
[Feature] Сделать пример на client.operations_stream.positions_stream

### ISSUE THREAD

**Issue by AlexanderVolkovTCS** [Tinkoff/invest-python#113]
### Описание

У клиентов есть сложности с использованием operations_stream.positions_stream

### Желаемое решение

Реализовать пример в examples, реализующий работу с operations_stream.positions_stream

**Comment by sasha160495** [comment]
Также есть ошибка с "available_value" в классе "PositionsMoney".
Попробуйте изменить содержимое портфеля. Придет:
"AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'available_value'"
