### ISSUE TITLE
[Bug] Возвращаемый тип отличается от аннотированного

### ISSUE THREAD

**Issue by Maksim787** [Tinkoff/invest-python#114]
### Что случилось?

https://github.com/Tinkoff/invest-python/blob/d057bcbe42ad205b039c2c7f1de21d3161a018ea/tinkoff/invest/market_data_stream/async_market_data_stream_manager.py#L76

Аннотирован Awaitable[MarketDataResponse], но фактически возвращается MarketDataResponse

### Tinkoff Invest Version

0.2.0-beta35

### Python Version

3.10

### OS

Windows

**Comment by daxartio** [comment]
На самом деле Awaitable, просто используете скорее всего уже с синтаксисом async

```python
async fop market_data_response in AsyncMarketDataStreamManager():
    pass
```
