### ISSUE TITLE
[Bug] Не могу получить сообщения сделок (trades)

### ISSUE THREAD

**Issue by DmitriyGordeev** [Tinkoff/invest-python#123]
### Что случилось?

Не могу получить сообщения сделок (trades), вот пример. Если раскомментировать часть с Candles то все ок

```python
import asyncio
import os

from tinkoff.invest import (
    AsyncClient,
    CandleInstrument,
    TradeInstrument,
    MarketDataRequest,
    SubscribeCandlesRequest,
    SubscribeTradesRequest,
    SubscriptionAction,
    SubscriptionInterval,
)

FIGI = "BBG000N9MNX3"

TOKEN = "..."

async def main():
    async def request_iterator():
        # yield MarketDataRequest(
        #     subscribe_candles_request=SubscribeCandlesRequest(
        #         subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
        #         instruments=[
        #             CandleInstrument(
        #                 figi=FIGI,
        #                 interval=SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE,
        #             )
        #         ],
        #     )
        # )

        yield MarketDataRequest(
            subscribe_trades_request=SubscribeTradesRequest(
                subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                instruments=[
                    TradeInstrument(figi=FIGI)
                ]
            )
        )

        while True:
            await asyncio.sleep(1)

    async with AsyncClient(TOKEN) as client:
        async for marketdata in client.market_data_stream.market_data_stream(
            request_iterator()
        ):
            print(marketdata)


if __name__ == "__main__":
    asyncio.run(main())
```

Единственное что он выводит в консоль:
`MarketDataResponse(subscribe_candles_response=None, subscribe_order_book_response=None, subscribe_trades_response=SubscribeTradesResponse(tracking_id='63329280ac0120882046d8d4481471b1', trade_subscriptions=[TradeSubscription(figi='BBG000N9MNX3', subscription_status=<SubscriptionStatus.SUBSCRIPTION_STATUS_SUCCESS: 1>)]), subscribe_info_response=None, candle=None, trade=None, orderbook=None, trading_status=None, ping=None, subscribe_last_price_response=None, last_price=None)`

но ждал достаточно времени, чтобы появились какие-то другие сообщения. Ранее подобный код работал и я видел сообщения сделок. Нужны ли изменения?

### Tinkoff Invest Version

0.2.0-beta36

### Python Version

3.9

### OS

Windows

**Comment by irusland** [comment]
Подскажите, что выдает скрипт:

```python
import asyncio
import os

from tinkoff.invest import (
    AsyncClient,
)
from tinkoff.invest import InstrumentIdType, ShareResponse, TradingSchedulesResponse
from tinkoff.invest.utils import now

TOKEN = os.environ["INVEST_TOKEN"]

FIGI = "BBG000N9MNX3"


async def main():
    async with AsyncClient(TOKEN) as client:
        share_response: ShareResponse = await client.instruments.share_by(
            id_type=InstrumentIdType.INSTRUMENT_ID_TYPE_FIGI, id=FIGI
        )
        response: TradingSchedulesResponse = await client.instruments.trading_schedules(
            exchange=share_response.instrument.exchange,
            from_=now(),
            to=now(),
        )
        (exchange,) = response.exchanges
        (day,) = exchange.days
        info = dict(
            is_trading_day=day.is_trading_day,
            start_time=day.start_time,
            now=now(),
            end_time=day.end_time,
            is_able_to_trade=day.is_trading_day and day.start_time < now() < day.end_time,
        )
        for k, v in info.items():
            print(f"{k:>20} {v}")


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by DmitriyGordeev** [comment]
Прошу прощения за долгий ответ, скрипт который вы прислали выше выдает вот такое:

is_trading_day True
          start_time 2022-11-09 07:00:00+00:00
                 now 2022-11-09 14:10:52.784476+00:00
            end_time 2022-11-09 22:45:00+00:00
    is_able_to_trade True
    
Я только что сделал чистую переустановку tinkoff.invest и проблема с трейдами решилась. Если честно сам не понял в чем была проблема, возможно косяк был на моей стороне, прошу прощения за беспокойство

Сейчас вижу приходящие трейды:

MarketDataResponse(subscribe_candles_response=None, subscribe_order_book_response=None, subscribe_trades_response=None, subscribe_info_response=None, candle=None, trade=Trade(figi='BBG000N9MNX3', direction=<TradeDirection.TRADE_DIRECTION_SELL: 2>, price=Quotation(units=191, nano=390000000), quantity=30, time=datetime.datetime(2022, 11, 9, 14, 20, 24, 187171, tzinfo=datetime.timezone.utc)), orderbook=None, trading_status=None, ping=None, subscribe_last_price_response=None, last_price=None)

MarketDataResponse(subscribe_candles_response=None, subscribe_order_book_response=None, subscribe_trades_response=None, subscribe_info_response=None, candle=None, trade=Trade(figi='BBG000N9MNX3', direction=<TradeDirection.TRADE_DIRECTION_SELL: 2>, price=Quotation(units=191, nano=390000000), quantity=20, time=datetime.datetime(2022, 11, 9, 14, 20, 24, 187311, tzinfo=datetime.timezone.utc)), orderbook=None, trading_status=None, ping=None, subscribe_last_price_response=None, last_price=None)

MarketDataResponse(subscribe_candles_response=None, subscribe_order_book_response=None, subscribe_trades_response=None, subscribe_info_response=None, candle=None, trade=Trade(figi='BBG000N9MNX3', direction=<TradeDirection.TRADE_DIRECTION_SELL: 2>, price=Quotation(units=191, nano=400000000), quantity=50, time=datetime.datetime(2022, 11, 9, 14, 20, 24, 187552, tzinfo=datetime.timezone.utc)), orderbook=None, trading_status=None, ping=None, subscribe_last_price_response=None, last_price=None)

MarketDataResponse(subscribe_candles_response=None, subscribe_order_book_response=None, subscribe_trades_response=None, subscribe_info_response=None, candle=None, trade=Trade(figi='BBG000N9MNX3', direction=<TradeDirection.TRADE_DIRECTION_SELL: 2>, price=Quotation(units=191, nano=400000000), quantity=80, time=datetime.datetime(2022, 11, 9, 14, 20, 24, 187449, tzinfo=datetime.timezone.utc)), orderbook=None, trading_status=None, ping=None, subscribe_last_price_response=None, last_price=None)

**Comment by irusland** [comment]
решили
