### ISSUE TITLE
[Bug] failed to connect to all addresses; last error: UNKNOWN: tcp handshaker shutdown

### ISSUE THREAD

**Issue by koblents** [Tinkoff/invest-python#129]
### Что случилось?

При попытке получения сделок/аккаунтов периодически выпадает ошибка - это какие-то проблемы на стороне API или я что-то делаю не так?

tinkoff.invest.exceptions.RequestError: (<StatusCode.UNAVAILABLE: (14, 'unavailable')>, 'failed to connect to all addresses; last error: UNKNOWN: tcp handshaker shutdown', None)

### Tinkoff Invest Version

0.2.0-beta36

### Python Version

3.8

### OS

Mac OS

**Comment by TheLegionCrazy** [comment]
сервак у них упал походу, у меня тож такая тема

**Comment by irusland** [comment]
Прикладывайте к issue шаги воспроизведения, пожалуйста.

Скрипт
```python
with Client(token) as client:
    response = client.users.get_accounts()
    print(response)
    account, *_ = response.accounts
    print(client.orders.get_orders(account_id=account.id))
```
Выполняется успешно.

Откройте проблему заново если проблемы будут наблюдаться вновь.

**Comment by marperia** [comment]
> Прикладывайте к issue шаги воспроизведения, пожалуйста.
> 
> Скрипт
> 
> ```python
> with Client(token) as client:
>     response = client.users.get_accounts()
>     print(response)
>     account, *_ = response.accounts
>     print(client.orders.get_orders(account_id=account.id))
> ```
> 
> Выполняется успешно.
> 
> Откройте проблему заново если проблемы будут наблюдаться вновь.

Ровно та же ситуация. Повесили получение ордеров на крон (они должны постоянно обновляться), десять-двадцать раз в сутки получаем ошибку. Чиниться как-то?
