### ISSUE TITLE
[Feature] make -> poethepoet

### ISSUE THREAD

**Issue by irusland** [Tinkoff/invest-python#148]
### Описание

В [дискуссии](https://github.com/Tinkoff/invest-python/pull/140#discussion_r1021600090) предлагается с make перейти на кроссплатформенный инструмент

### Желаемое решение

перейти на общее решение unix и windows систем для выполнения make команд

**Comment by daxartio** [comment]
#175 добавил make на windows хост

**Comment by daxartio** [comment]
#175 добавил make на windows хост
