### ISSUE TITLE
[Feature] auto bump version

### ISSUE THREAD

**Issue by irusland** [Tinkoff/invest-python#155]
### Описание

Убрали пуш в мастер, поэтому требуется автоматизировать действия по выкачу новой версии в ci в виде джобы пайплайне

### Желаемое решение

сделать шаг make bump-version, который бы генерил описание релиза и сохранял тег в гите

### Дополнительно

реализовать возможность джобу запускать на мастере принудительно и отдельно от других джоб

**Comment by daxartio** [comment]
#175 немного поменял процесс выпуска новой версии. Теперь тэг надо ставить в мастере
