### ISSUE TITLE
[Bug] MarketDataStream error

### ISSUE THREAD

**Issue by artemtyupov** [Tinkoff/invest-python#160]
### Что случилось?

При итерации market_data_stream иногда стрим выбрасывает ошибку, скрин ошибки прилагаю.
![err](https://user-images.githubusercontent.com/22501914/205593741-98a253f8-14d6-421b-9727-dd682f08fc13.png)

### Воспроизведение

```python
1. Создание client: AsyncClient
2. Создание mds: MarketDataStream через client.create_market_data_stream()
3. Подписка на события через mds.candles.subscribe и mds.info.subscribe
4. Начало итерации по стриму через async for
5. Через n-ое кол-во времени вылетает ошибка. Иногда через день, иногда через 2, иногда через 10 минут. Никаких закономерностей не обнаружил.
```

### Tinkoff Invest Version

0.2.0-beta43

### Python Version

3.10

### OS

Windows

**Comment by irusland** [comment]
Запустил эксперимент

**Comment by artemtyupov** [comment]
Спасибо!
Вчера опять упал стрим, спустя 28 часов где-то

**Comment by artemtyupov** [comment]
Ошибка та же

**Comment by irusland** [comment]
Извиняюсь за долгий ответ. 

По результатам эксперимента выяснилось, что разрывы происходят не так часто, за неделю соединение разорвалось 2 раза
1) 12 часов после запуска
2) 3.5 дня после предыдущего падения

Клиент получил ответов 143 574
Сервер обработал 99.999+% ответов.

Завел новый тикет https://github.com/Tinkoff/invest-python/issues/177. Этот закрываю
