### ISSUE TITLE
В документации API не совсем понятно как подписаться сразу на несколько стримов

### ISSUE THREAD

**Issue by qqStardy** [Tinkoff/invest-python#165]
### Что случилось?

Не совсем понимаю как подписаться сразу на несколько стримов, в примерах не нашёл.
Как это делать правильно?
Попробовал так, не получилось:

### Воспроизведение

```python
async def request_iterator():
        yield MarketDataRequest(
            subscribe_candles_request=SubscribeCandlesRequest(
                waiting_close=True,
                subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                instruments=[
                    CandleInstrument(
                        figi="BBG004730RP0",
                        interval=SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE,
                    )
                    #for figi in figies
                ],
            ),
            subscribe_order_book_request=SubscribeOrderBookRequest(
                subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                instruments=[
                    OrderBookInstrument(
                        figi = "BBG004730RP0",
                        depth = 50
                    )
                    #for figi in figies
                ],
            )
        )
        while True:
            await asyncio.sleep(1)
```

### Tinkoff Invest Version

0.2.0-beta43

### Python Version

3.10

### OS

Windows

**Comment by daxartio** [comment]
Что значит несколько стримов?
Например подписаться на:
- market_data_stream
- operations_stream
- orders_stream?

**Comment by qqStardy** [comment]
![image](https://user-images.githubusercontent.com/93968798/208679096-fac42186-35be-4760-b02e-36016c4d4a8b.png)
В документации написано что можно подписаться на несколько стримов market_data, но в примерах я не нашёл как это сделать, единственное что нашёл это одно stream-соединение
![image](https://user-images.githubusercontent.com/93968798/208679079-144ccc2e-4fa9-485a-95ef-cd668b1c9ad6.png)

**Comment by irusland** [comment]
Взгляните на пример https://github.com/Tinkoff/invest-python/blob/main/examples/easy_stream_client.py здесь подписка по осуществляется на разные типы данных, info и candles

**Comment by daxartio** [comment]
Да, или можно несколько раз передать Request через yield в генераторе
