### ISSUE TITLE
[Feature] Добавить в информацию об облигации признак субординированной облигации

### ISSUE THREAD

**Issue by JonS87** [Tinkoff/invest-python#172]
### Описание

В bonds и bondby отсутствует признак субординированной облигации, по которому можно фильтровать облигации в скринере облигаций
![20230101_214454](https://user-images.githubusercontent.com/91465032/210181635-0f70841b-032f-4d5e-bc6e-38f778b2230f.jpg)

### Желаемое решение

Добавить в информацию об облигации признак субординированной облигации

**Comment by irusland** [comment]
Есть ли данный признак в контрактах Invest OpenAPI? https://github.com/Tinkoff/invest-openapi

Если нет - то стоит перенести issue туда на рассмотрение, а мы поддержим новое поле информации, когда его реализуют.

**Comment by AlexanderVolkovTCS** [comment]
Добавлено
