### ISSUE TITLE
Выгружаю облигации которые не доступны к покупке[Bug] 

### ISSUE THREAD

**Issue by JonS87** [Tinkoff/invest-python#174]
### Что случилось?

с помощью метода bonds(instrument_status = 2) выгружаю список облигаций имеющихся в тинькофф, дальше фильтрую полученный результат по следующим критериям:
p.country_of_risk == 'RU'
and p.buy_available_flag == True
and p.sell_available_flag == True
and p.amortization_flag == False
and p.for_qual_investor_flag == False
а на выходе получаю облигации которые в самом тинькофф инвестициях не доступны к торговле по техническим причинам, например RU000A102AK9

### Tinkoff Invest Version

0.2.0-beta44

### Python Version

3.9

### OS

Windows

**Comment by AlexanderVolkovTCS** [comment]
>с помощью метода bonds(instrument_status = 2)

Если вам нужны торгуемые облигации, то выгружайте со статусом instrument_status = 1 (INSTRUMENT_STATUS_BASE)
