### ISSUE TITLE
Кеширование

### ISSUE THREAD

**Issue by daxartio** [Tinkoff/invest-python#18]
Есть необходимость кешировать данные.

Добавить кеши для:
...

Кеши хранить на диске, чтобы после рестарта, можно было использовать их.
Также добавить хранение в памяти.

Кеши хранить в протоформате.

**Comment by t2016** [comment]
При использовании кэша столкнулся с проблемой:

  File "/usr/local/lib/python3.10/site-packages/tinkoff/invest/services.py", line 248, in get_all_candles
    yield from self._with_saving_into_cache(
  File "/usr/local/lib/python3.10/site-packages/tinkoff/invest/services.py", line 209, in _with_saving_into_cache
    str(min(list(map(lambda x: x.time, candles)))),

 settings = MarketDataCacheSettings(base_cache_dir=Path(".market_data_cache"))
market_data_cache = MarketDataCache(settings=settings, services=local_client)

candles = market_data_cache.get_all_candles(
            figi=local_figi,
            from_=now() - timedelta(days=local_day),
            interval=local_interval,
        )

**Comment by irusland** [comment]
Пока не понял проблему, откройте, пожалуйста новую issue и опишите проблему подробнее с шагами к воспроизведению
