### ISSUE TITLE
Ошибка <StatusCode.UNAVAILABLE: (14, "unavailable')>, "upstream request timeout", Metadata(tracking_id=None, ratelimit_limit="300, 300;w=60", ratelimit_remaining=273, ratelimit_reset=31, message=None))

### ISSUE THREAD

**Issue by qqStardy** [Tinkoff/invest-python#186]
### Что случилось?

При попытке получить все свечи за определённый период, появилась ошибка, в связи с чем она связана?
![image](https://user-images.githubusercontent.com/93968798/215795120-85bd75b7-9b09-4286-8297-e09f4cdad1a6.png)

### Tinkoff Invest Version

0.2.0-beta47

### Python Version

3.11

### OS

Windows

**Comment by qqStardy** [comment]
Появилась новая проблема, ошибка <StatusCode.UNKNOWN: (2, 'unknown')>, 'Stream removed', Metadata(tracking_id='63c8bf17b8eb55ba3cd76f67a44532b3', ratelimit_limit='300, 300;w=60', ratelimit_remaining=265, ratelimit_reset=29, message=None
![image](https://user-images.githubusercontent.com/93968798/216401221-5bfbd498-b4da-4ed0-ab98-495bfa1a7d5b.png)
С чем может быть связано?

**Comment by hyperclick** [comment]
та же проблема при вызове GetOrderBook
<StatusCode.UNAVAILABLE: (14, 'unavailable')>, 'upstream request timeout', Metadata(tracking_id=None, ratelimit_limit='300, 300;w=60', ratelimit_remaining=283, ratelimit_reset=52, message=None)
что означают ratelimit_limit='300, 300;w=60', ratelimit_remaining=283, ratelimit_reset=52 ?

**Comment by AlexanderVolkovTCS** [comment]
В это время были сетевые инциденты.
