### ISSUE TITLE
проблема с подключением

### ISSUE THREAD

**Issue by IvanKron** [Tinkoff/invest-python#19]
Добрый день.

Вопрос  очень примитивный, но буду признателен за совет.

в локальном jupyter notebooks выполнил установку
!pip install tinkoff-investments

импортировал в локальную переменную токен

import os
os.environ["INVEST_TOKEN"] =#указал здесь свой токен. пробовал токен песочницы и боевой

Пытаюсь выполнить пример [client.py](https://github.com/Tinkoff/invest-python/blob/main/examples/client.py)

но получаю
40982fba45e663c72c049baad9b64aaf GetAccounts UNAUTHENTICATED 

RequestError: (<StatusCode.UNAUTHENTICATED: (16, 'unauthenticated')>, '', Metadata(tracking_id='40982fba45e663c72c049baad9b64aaf', ratelimit_limit='100, 100;w=60', ratelimit_remaining=98, ratelimit_reset=30, message='Authentication failed'))

Видимо мне нужно выполнить аутентификацию до запуска примеров. Подскажите, пожалуйста, как это сделать? Или где можно почитать про это?

Спасибо.

**Comment by daxartio** [comment]
Не совсем понятно, что вы хотите. Скиньте код полный

**Comment by IvanKron** [comment]
Оказалось, что проблема в токенах. У меня были сгенерированы токены в сентябре 2021 года (на запись и песочница). Если их использовать, появляется эта ошибка 

40982fba45e663c72c049baad9b64aaf GetAccounts UNAUTHENTICATED

Сгенерировал сейчас новый токен readonly (это новый тип, в сентябре вроде бы такого не было). Подставил его в код TOKEN = "Ваш токен"

и код ниже заработал. 
with Client(TOKEN) as client:
    print(client.users.get_accounts())

Зашёл посмотреть список токенов по ссылке https://id.tinkoff.ru/account увидел там только один токен, который создал сегодня. Видимо старые токены от сентября 2021 удалились по неактивности и поэтому не работали больше.

Спасибо за ответы. Буду дальше разбираться.
