### ISSUE TITLE
tracking_id выполненных запросов

### ISSUE THREAD

**Issue by andrey-vrn** [Tinkoff/invest-python#194]
### Что случилось?

Подскажите, как включить логирование tracking_id выполненных запросов? Вижу по коду logging.py, что логирование tracking_id предусмотрено, но не понял, как правильно использовать этот функционал.

### Tinkoff Invest Version

0.2.0-beta48

### Python Version

3.10

### OS

Linux

**Comment by irusland** [comment]
Идею можно подчеркнуть в примере https://github.com/Tinkoff/invest-python/blob/main/examples/logger.py

**Comment by andrey-vrn** [comment]
Спасибо!
