### ISSUE TITLE
Ошибка при выполнении запроса get_all_candles

### ISSUE THREAD

**Issue by sfaxi19** [Tinkoff/invest-python#20]
При получении истории свечей возникает ошибка:
`
tinkoff.invest.exceptions.RequestError: (<StatusCode.INVALID_ARGUMENT: (3, 'invalid argument')>, '30012', Metadata(tracking_id='849485810b568de052ac312ec9de2379', ratelimit_limit='200, 200;w=60', ratelimit_remaining=183, ratelimit_reset=15, message="'to' can't be less then 'from'"))
`

Выполняемый код:
```
import os
from datetime import datetime, timedelta
from tinkoff.invest import CandleInterval, Client

token = os.getenv('TIN_TOKEN', '')


def main():
    with Client(token) as client:
        for candle in client.get_all_candles(
            figi="BBG000BBJQV0",
            from_=datetime.utcnow() - timedelta(days=3),
            interval=CandleInterval.CANDLE_INTERVAL_1_MIN,
        ):
            print(candle)

if __name__ == "__main__":
    main()
```

**Comment by sfaxi19** [comment]
У себя временно пофиксил обнулением микросекунд:
```
from_day = (datetime.utcnow() - timedelta(days=3)).replace(microsecond=0)
to_day = datetime.utcnow().replace(microsecond=0)
```

**Comment by daxartio** [comment]
Ок. Спасибо, что написали.
На неделе исправим

**Comment by daxartio** [comment]
https://github.com/Tinkoff/investAPI/issues/94

**Comment by irusland** [comment]
#29
