### ISSUE TITLE
[Bug] Несоответствие данных рейтинга инструмента действительным

### ISSUE THREAD

**Issue by vovabush** [Tinkoff/invest-python#204]
### Что случилось?

Библиотека возвращает рейтинг инструмента RU000A105QL6 равный 0 - не определен. 

При этом в приложении рейтинг явно указан как 2:

<img src="https://user-images.githubusercontent.com/3701803/223646390-a5ad7405-ef46-4d35-8e09-8822b7ae797b.png" width="50%" height="50%"/>

### Воспроизведение

```Python
with Client(TOKEN) as client:
    print(client.instruments.bond_by(id_type=2, class_code='TQIR', id='RU000A105QL6').instrument.risk_level.value)
```

### Tinkoff Invest Version

0.2.0-beta50

### Python Version

3.10

### OS

Windows

**Comment by vovabush** [comment]
Также для примера у инструмента `RU000A104VS4` в приложении рейтинг Высокий, а библиотека возвращает 1, что в соответствии с [документацией](https://tinkoff.github.io/investAPI/instruments/#risklevel) говорит о том, что рейтинг Низкий.

**Comment by FerrusM** [comment]
> Также для примера у инструмента `RU000A104VS4` в приложении рейтинг Высокий, а библиотека возвращает 1, что в соответствии с [документацией](https://tinkoff.github.io/investAPI/instruments/#risklevel) говорит о том, что рейтинг Низкий.

В приложении отображается рейтинг компании, а API возвращает уровень риска. В этом примере нет ошибки: рейтинг компании высокий, соответственно, уровень риска низкий.
По той же причине нет никакого бага в том, что приложение отображает рейтинг там, где API не возвращает риск. Риск может рассчитываться исходя не только из рейтинга компании.

**Comment by vovabush** [comment]
Спасибо, разобрался, исправил, Issue можно тогда закрыть.
