### ISSUE TITLE
[Bug] Не хватает атрибутов в методе find_instrument

### ISSUE THREAD

**Issue by Ipsilon91** [Tinkoff/invest-python#233]
### Что случилось?

В методе find_instrument не хватает атрибутов api_trade_available_flag и instrument_kind, которые есть в API (https://tinkoff.github.io/investAPI/instruments/#findinstrumentrequest). Есть только атрибут query.

![find_instrument](https://github.com/Tinkoff/invest-python/assets/20323211/b5190be4-60a1-4cc2-8a48-699e93c7c682)

### Tinkoff Invest Version

0.2.0-beta57

### Python Version

3.8

### OS

Windows

**Comment by daxartio** [comment]
Fixed in 0.2.0b58
