### ISSUE TITLE
Зависимость пакета при установке через Poetry или pip от  pydantic (>=1.9.2,<2.0.0)

### ISSUE THREAD

**Issue by DipodDP** [Tinkoff/invest-python#241]
### Что случилось?

При попытке установить в одном проекте пакеты `tinkoff-investments` и `pydantic (>=2.0.0)`, пакетный менеджер выдает ошибку:
```sh
Because no versions of pydantic-settings match >2.0.2,<3.0.0
 and pydantic-settings (2.0.2) depends on pydantic (>=2.0.1), pydantic-settings (>=2.0.2,<3.0.0) requires pydantic (>=2.0.1).
And because tinkoff-investments (0.2.0b58) depends on pydantic (>=1.9.2,<2.0.0)
 and no versions of tinkoff-investments match >0.2.0b58,<0.3.0, pydantic-settings (>=2.0.2,<3.0.0) is incompatible with tinkoff-investments (>=0.2.0b58,<0.3.0).

So, because test_project depends on both tinkoff-investments (^0.2.0b58) and pydantic-settings (^2.0.2), version solving failed.
```
хотя `tinkoff-investments`, кажется, не зависит от `pydantic`. 
По крайней мере `pydantic (>=2.0.0)` без проблем ставится в окружение склонированного репозитория `tinkoff-investments`.

### Воспроизведение

```Python
# Ошибка
$ poetry add tinkoff-investments
$ poetry add pydantic-settings # Любой пакет, зависящий от pydantic (>=2.0.0)

# Без ошибок
$ git clone tinkoff-investments
$ cd tinkoff-investments
$ poetry add pydantic-settings
```

### Tinkoff Invest Version

0.2.0-beta58

### Python Version

3.11

### OS

Linux

**Comment by daxartio** [comment]
Странно, но у нас нигде нет зависимости от pydantic

**Comment by irusland** [comment]
> Странно, но у нас нигде нет зависимости от pydantic

Похоже что релизный воркфлоу не триггернулся на мастере после того, как я пидантик убрал(

**Comment by irusland** [comment]
Последняя релейная версия (0.2.0-beta58) была выкачена в мае. Как заставить его релизнуться?

**Comment by daxartio** [comment]
Достаточно запустить Bump в github actions

Я уже запустил в 0.2.0-beta59 должно быть все норм

**Comment by DipodDP** [comment]
Да, теперь poetry смог поставить пакет
