### ISSUE TITLE
Не нашел API для получения амортизации облигаций

### ISSUE THREAD

**Issue by fast-runner** [Tinkoff/invest-python#243]
### Что случилось?

Какое API использовать чтобы получить даты и суммы возврата тела = снижения номинала по облигации?

### Tinkoff Invest Version

0.2.0-beta58

### Python Version

3.11

### OS

Windows

**Comment by AlexanderVolkovTCS** [comment]
будет решено в рамках https://github.com/Tinkoff/investAPI/issues/442

**Comment by FerrusM** [comment]
связанная тема Tinkoff/invest-python#86
