### ISSUE TITLE
пожалуйста сбилдите под arm!Mac m1 

### ISSUE THREAD

**Issue by MURSHIG** [Tinkoff/invest-python#25]
ImportError: dlopen(/Users/muratsigalugov/Desktop/tinkoff-invest-bot/venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/muratsigalugov/Desktop/tinkoff-invest-bot/venv/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)

**Comment by daxartio** [comment]
Добрый день
Посмотрите этот issue https://github.com/grpc/grpc/issues/25082
Кажется нужно просто проставить флаги в среду
