### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by WhyBullyMe** [Tinkoff/invest-python#27]
1)В терминале ввел pip install tinkoff-investments
2)В .py файле ввел пример 
3) Выдает ошибки Unresolved reference 'tinkoff','Client'
Я только начал, а у меня уже ничего не получается

**Comment by daxartio** [comment]
скинь пример
скорее всего написал неправильно путь и возможно структура проекта не та

**Comment by WhyBullyMe** [comment]
Вот на скрине что от pip install tinkoff-investments, насколько понял просто написать надо было что с примера и заработает (в данном случае тупо в мейн написал). Токен еще не вставлял, т.к. надо сначала с этой проблемой разобраться.[https://imgur.com/UvrJ7hZ](url). Если там не понятно лучше по пунктам объясните что и как

**Comment by daxartio** [comment]
скиньте скрин сюда

**Comment by WhyBullyMe** [comment]
![Безымянный](https://user-images.githubusercontent.com/101263903/157481246-19bcccdc-7e9b-4b0b-9745-d4ac244e697b.png)

**Comment by daxartio** [comment]
Настройте среду)
В этом репозитории таких подсказок не будет.
