### ISSUE TITLE
Публикация пакета в test.pypi

### ISSUE THREAD

**Issue by daxartio** [Tinkoff/invest-python#31]
Ветку `develop` стоит опубликовать в тестовом режистри. Чтобы пользователи уже могли тестировать функционал.

**Comment by 0dminnimda** [comment]
`test.pypi` существует не для этого. Он сществует, чтобы проверять, что с пакетом всё ок, и его можно публиковать. Из [доков](https://packaging.python.org/en/latest/guides/using-testpypi/#using-testpypi):
> TestPyPI is a separate instance of the [Python Package Index (PyPI)](https://packaging.python.org/en/latest/glossary/#term-Python-Package-Index-PyPI) that allows you to try out the distribution tools and process without worrying about affecting the real index

Если есть желание установить последнюю, не стабильную версию пакета из гитхаба, можно воспользоваться флагом для pip: `pip install git+https://github.com/Tinkoff/invest-python.git`

**Comment by daxartio** [comment]
Да, все так. Можно также выгладывать альфа версии на pypi. Я точно не уверен, что pip умеет работать с poetry lock файлом при установке через гит. Хотелось бы добавить только возможность публиковать пакет на test pypi для проверки его целостности. Но конечно это не приоритет.
