### ISSUE TITLE
Документация на SDK

### ISSUE THREAD

**Issue by dsenash** [Tinkoff/invest-python#33]
### Что случилось?

Не могу сказать, что я супер гуру по современным средствам разработки. Может быть поэтому я никак не могу разобраться в самом Python SDK.
Документации или нет или я ее не могу найти.
Например:
Вот беру пример client.py
Вижу print(client.users.get_accounts()). Оригинальный запрос в API - GetAccounts из UsersService.
Пытаюсь аналогично получить список фьючерсов. Он в инструментах.
print(client.instruments.get_futures(instrument_status=INSTRUMENT_STATUS_ALL))-  получаю: 'InstrumentsService' object has no attribute 'get_futures'
Предполагаю, надо что-то дополнительно импортнуть. Но что?
Где можно найти доку по официальной Python SDK?  Какой метод соответствует чему в API? И как его вызывать?
В примерах нет ни операций, ни акций, ни фьюч, ни размещения ставки. 
Или я как-то не так ищу? Спасибо.

### Воспроизведение

1. Шаг 1
1. Шаг 2

### Version

0.2.0-beta19

### OS

Linux

**Comment by dsenash** [comment]
Разобрал services.py и нашел, что get было лишнее. Совершенно не очевидно.
Т.е. правильный запрос был print(client.instruments.futures(instrument_status=0))
Но это в целом ненаучно и мне все таки кажется, что дока по SDK нужна.

**Comment by daxartio** [comment]
Попробую отметить, что sdk полностью копирует прото файлы. То есть, надо будет это как то писать.
Доку со временем сделаем. Будет документация по api

**Comment by AlexanderVolkovTCS** [comment]
Документация по python sdk: https://tinkoff.github.io/invest-python/
Общая документация по API: https://tinkoff.github.io/investAPI/
