### ISSUE TITLE
[Issue] Господа! client.get_all_candles возвращает int. Причина? 

### ISSUE THREAD

**Issue by sneakybeaky18** [Tinkoff/invest-python#38]
### Что случилось?

Хотелось бы возвращать значения в float. Это возможно?

```
# tinkoff.invest.schemas 

@dataclass(eq=False, repr=True)
class Quotation(_grpc_helpers.Message):
    units: int = _grpc_helpers.int64_field(1)
    nano: int = _grpc_helpers.int32_field(2)

```

### Воспроизведение

```

def main():
    global TOKEN 
    with Client(TOKEN) as client:
        for candle in client.get_all_candles(
            figi="BBG004730N88", #BBG000B9XRY4
            from_=datetime.utcnow() - timedelta(days=15),
            interval=CandleInterval.CANDLE_INTERVAL_15_MIN,
        ):
            print(candle.high.units)
            print(candle)
            break
             

    return 0

if __name__ == "__main__":
    main()

```

### Tinkoff Invest Version

0.2.0-beta19

### Python Version

3.10

### OS

Windows

**Comment by daxartio** [comment]
Это невозможно

**Comment by daxartio** [comment]
Почитайте про этот тип. Нужно самим переводить в float, опираясь на то, как хотите его использовать. В будущем, может сделаем свой метод для первода, чтобы было удобнее пользоваться

**Comment by HappyManRus** [comment]
Поддержу идею создания своего метода. Пока нарисовал свой, но иметь штатный в SDK - приятнее.

**Comment by sneakybeaky18** [comment]
> Почитайте про этот тип. Нужно самим переводить в float, опираясь на то, как хотите его использовать. В будущем, может сделаем свой метод для первода, чтобы было удобнее пользоваться

Понятно

**Comment by sneakybeaky18** [comment]
> Почитайте про этот тип. Нужно самим переводить в float, опираясь на то, как хотите его использовать. В будущем, может сделаем свой метод для первода, чтобы было удобнее пользоваться

Понятно
