### ISSUE TITLE
[Feature] Как корректно параллельно слушать несколько streams?

### ISSUE THREAD

**Issue by HappyManRus** [Tinkoff/invest-python#41]
### Описание

Добрый день.
Перехожу на потоки, и возник вопрос - как оптимально ими пользоваться. 
У меня в задачах, получать параллельно:
1. минутные свечи  (10-30 активов)
2. часовые свечи (30-60 активов)
3. выставлять новые торговые поручения (покупка-продажа)
4. следить за сделками (покупка-продажа)
5. отслеживать стаканы по единичным активам (до 15 активов)

### Желаемое решение

Как корректно организовать прослушивание такого набора потоков, минимизировав количество подключений?
Есть пример реализации параллельно в одном модуле нескольких перечисленных пунктов?
В приложении пример, который набросал исходя из своих скромных знаний. Реализует пункты 1 и 4. Он корректный? Или можно как-то оптимизировать/улучшить?
Хочется сразу заложить корректное ядро, которое минимизирует кол-во подключений к серверу, а также будет устойчиво в части восстановления подключений при сбоях любого характера.
Думаю подобный пример от разработчикам SDK будет полезен многим клиентам, и **сократит** лишнюю нагрузку на сервера.

### Дополнительно

```
import asyncio

from tinkoff.invest import (
    AsyncClient,
    CandleInstrument,
    MarketDataRequest,
    SubscribeCandlesRequest,
    SubscriptionAction,
    SubscriptionInterval
)
from tinkoff.invest.token import TOKEN


async def MarketData_iter():
    async def request_iterator():
        yield MarketDataRequest(
            subscribe_candles_request=SubscribeCandlesRequest(
                subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                instruments=[
                    CandleInstrument(
                        figi="BBG004730N88",
                        interval=SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE,
                    )
                ],
            )
        )
        while True:
            await asyncio.sleep(30)

    async with AsyncClient(TOKEN) as client:
        try:
            async for marketdata in client.market_data_stream.market_data_stream(request_iterator()):
                print(marketdata)
        except:
            print('error in market_data_stream')
            await asyncio.sleep(100)


async def TradesData():
    async with AsyncClient(TOKEN) as client:
        try:
            async for tradesdata in client.orders_stream.trades_stream():
                print(tradesdata)
                await asyncio.sleep(1)
        except:
            print('error in orders_stream')
            await asyncio.sleep(100)


async def check_state(ioloop):
    while True:
        print(ioloop.is_running())
        await asyncio.sleep(300)

if __name__ == "__main__":
    while True:
        ioloop = asyncio.get_event_loop()
        tasks = [ioloop.create_task(MarketData_iter()),
                 ioloop.create_task(TradesData()),
                 ioloop.create_task(check_state(ioloop))]
        wait_tasks = asyncio.wait(tasks)
        ioloop.run_until_complete(wait_tasks)
        ioloop.close()
```

**Comment by daxartio** [comment]
Посмотрите новый пример easy stream. Там не нужно удерживать итератор на подписки и отписки

**Comment by HappyManRus** [comment]
@daxartio Хорошо, спасибо! изучу Queue и пример  easy stream.
(задачу закрываю)
