### ISSUE TITLE
[Issue] Неочевидное поведение при запросе get_all_candles

### ISSUE THREAD

**Issue by applepolice** [Tinkoff/invest-python#43]
### Что случилось?

Сегодня (19.04) начали немного странно работать выборки по свечам.
При запросе с 17.04 по 19.04  возвращается две дневных свечи, за 18.04 и 19.04, это ок.
При аналогичном запросе с 18.04 по 19.04 ожидаю увидеть сегодняшнюю дневную свечу (19.04) - но не возвращается ни одной.

### Воспроизведение

Выполняемый код:
```
import asyncio
from datetime import datetime, timedelta

from tinkoff.invest import AsyncClient, CandleInterval
from tinkoff.invest.token import TOKEN


async def main():
    async with AsyncClient(TOKEN) as client:
        print(f'This selection goes from {datetime.today() - timedelta(days=2)} to {datetime.today()}')
        async for candle in client.get_all_candles(
            figi="BBG004S68BR5",
            from_=datetime.today() - timedelta(days=2),
            to=datetime.today(),
            interval=CandleInterval.CANDLE_INTERVAL_DAY,
        ):
            print(candle.volume, candle.time)

        print(f'This selection goes from {datetime.today() - timedelta(days=1)} to {datetime.today()}')
        async for candle in client.get_all_candles(
            figi="BBG004S68BR5",
            from_=datetime.today() - timedelta(days=1),
            to=datetime.today(),
            interval=CandleInterval.CANDLE_INTERVAL_DAY,
        ):
            print(candle.volume, candle.time)



if __name__ == "__main__":
    asyncio.run(main())
```

### Tinkoff Invest Version

0.2.0-beta20

### Python Version

3.9

### OS

Windows

**Comment by irusland** [comment]
Приветствую, не смог воспроизвести. Код выдает
```
This selection goes from 2022-04-19 10:23:31.638979 to 2022-04-21 10:23:31.639014
198865 2022-04-19 07:00:00+00:00
56687 2022-04-20 07:00:00+00:00
This selection goes from 2022-04-20 10:23:32.090617 to 2022-04-21 10:23:32.090650
56687 2022-04-20 07:00:00+00:00
```

**Comment by irusland** [comment]
В какое время проблема воспроизводится у вас?

**Comment by applepolice** [comment]
Прямо сейчас, например, воспроизводится. Вот результат выполнения кода:
`This selection goes from 2022-04-19 12:15:09.965186 to 2022-04-21 12:15:09.965186
198865 2022-04-19 07:00:00+00:00
56687 2022-04-20 07:00:00+00:00
11297 2022-04-21 07:00:00+00:00
This selection goes from 2022-04-20 12:15:10.107452 to 2022-04-21 12:15:10.107452`

Может ли быть дело в том, что вы выполняли код, когда торги еще не начались?

**Comment by irusland** [comment]
Понял в чем дело :)
Фикс https://github.com/Tinkoff/invest-python/pull/44

**Comment by irusland** [comment]
Очень интересный кейс, а выполните команду 
```python
print(datetime.today(), datetime.today())
```
и покажите результат

**Comment by applepolice** [comment]
`print(datetime.today(), datetime.today())`
Вернул такой результат:
`2022-04-21 13:15:12.459100 2022-04-21 13:15:12.459100`

**Comment by irusland** [comment]
Это очень интересно, а какой у вас процессор?

**Comment by irusland** [comment]
А этот код тоже возвращает 2 одинаковых времени?
```python
print(datetime.now(), datetime.now())
```

**Comment by applepolice** [comment]
Да, возвращает тоже два одинаковых времени:
`2022-04-21 13:20:15.178726 2022-04-21 13:20:15.178726`
Процессор Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 2001 МГц

**Comment by irusland** [comment]
А вот такое?
```python
print(datetime.now(), bool([i for i in range(int(10e7))]), datetime.now())
```

**Comment by irusland** [comment]
Видимо у вас очень мощный процессор :) 
Проблема при загрузке была в том, что я неправильно написал условие, которое не работало если разница между датами была ровно 1 день, у вас воспроизводилось, а у меня нет, так как у меня было чуть больше 1 дня

**Comment by applepolice** [comment]
На 9 секунд удалось озадачить проц :)
`2022-04-21 13:32:47.602390 True 2022-04-21 13:32:56.605672`

**Comment by irusland** [comment]
Фикс в мастере, можно пробовать

**Comment by applepolice** [comment]
Работает, спасибо!

**Comment by daxartio** [comment]
Я сейчас небольшие фиксы по проекту добавлю и мы запушим в pypi
