### ISSUE TITLE
Как парсить nano при возвращении последней цены?

### ISSUE THREAD

**Issue by cdies** [Tinkoff/invest-python#45]
### Что случилось?

Метод `market_data.get_last_prices()` возврщает `units` - целую часть и `nano` - дробную часть.
Вопрос такой, а как в `nano` отличить например 1 копейку от 10, если число заполняется нулями в ответе?

`{'units': 0, 'nano': 10000000}`

**Comment by cdies** [comment]
Ясно, нужно 7 нулей убрать, и будет точная цифра.

**Comment by irusland** [comment]
Можно попробовать использовать https://github.com/Tinkoff/invest-python/blob/89cf3419d881c6aaa33377336c3fe24dfccb3f84/tinkoff/invest/utils.py#L32

**Comment by cdies** [comment]
Спасибо.
