### ISSUE TITLE
[Bug] TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by DimartGit** [Tinkoff/invest-python#46]
### Что случилось?

Ошибка выполнения

  File "..\site-packages\tinkoff\invest\utils.py", line 27, in get_intervals
    while local_from + interval_timedelta <= to:

TypeError: can't compare offset-naive and offset-aware datetimes

### Воспроизведение

запустить файл из поставки https://github.com/Tinkoff/invest-python/blob/main/examples/all_candles.py

### Tinkoff Invest Version

0.2.0-beta21

### Python Version

3.9

### OS

Windows

**Comment by irusland** [comment]
https://github.com/Tinkoff/invest-python/pull/47
