### ISSUE TITLE
[Bug] TypeError: Protocols cannot be instantiated

### ISSUE THREAD

**Issue by DimartGit** [Tinkoff/invest-python#48]
### Что случилось?

Ошибка TypeError: Protocols cannot be instantiated при работе образца стратегии из поставки

### Воспроизведение

запустить файл из поставки ~/invest-python/examples/strategies/param-search.ipynb

Ошибка возникает при выполнении блока кода после "Обеспечить такой выбор через обращение к полю events в виде events(best_stock)".

Выполнено три итерации с результатами:
2022-02-01 20:00:00,000 INFO:5ee74bd2e50c67dab24fcde8494fe5ed GetCandles
2022-02-01 20:00:00,000 INFO:a3a5dc504ae68ebbf6d20c08d16b6196 GetCandles
2022-02-01 20:00:00,000 INFO:73d98cb7d9fb90ac14c53d3c57ca5ffc GetCandles

Получена ошибка: TypeError: Protocols cannot be instantiated

### Tinkoff Invest Version

0.2.0-beta21

### Python Version

3.9

### OS

Windows

### Логи

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_9120/2488483488.py in <module>
     32         )
     33         state = MovingAverageStrategyState()
---> 34         strategy = MovingAverageStrategy(
     35             settings=settings,
     36             account_manager=account_manager,

~\site-packages\tinkoff\invest\strategies\moving_average\strategy.py in __init__(self, settings, account_manager, state)
     44         state: MovingAverageStrategyState,
     45     ):
---> 46         super().__init__()
     47         self._data: List[CandleEvent] = []
     48         self._settings = settings

C:\ProgramData\Anaconda3\lib\typing.py in _no_init(self, *args, **kwargs)
   1081 
   1082 def _no_init(self, *args, **kwargs):
-> 1083     raise TypeError('Protocols cannot be instantiated')
   1084 
   1085 

TypeError: Protocols cannot be instantiated
```

**Comment by irusland** [comment]
Какая у вас версия питона?
Нашел, что такая проблема есть после версии 3.9.6 https://bugs.python.org/issue45121

**Comment by DimartGit** [comment]
python 3.9.7 в Anaconda

**Comment by irusland** [comment]
фикс https://github.com/Tinkoff/invest-python/pull/55

**Comment by irusland** [comment]
Еще можно сменить версию питона
