### ISSUE TITLE
[Issue] Ошибка trades_stream() 

### ISSUE THREAD

**Issue by bugagashkovich** [Tinkoff/invest-python#54]
### Что случилось?

Добрый день. Не удается реализовать подписку по orders_stream.trades_stream()
Изначально писал по аналогии с market_data_stream.market_data_stream()

Выдает ошибку TypeError: OrdersStreamService.trades_stream() takes 1 positional argument but 2 were given

Сравнил код:

def market_data_stream(
    self,
    request_iterator: Iterable[MarketDataRequest],
) -> Iterable[MarketDataResponse]:
    for response in self.stub.MarketDataStream(
        request_iterator=self._convert_market_data_stream_request(request_iterator),
        metadata=self.metadata,
    ):
        yield _grpc_helpers.protobuf_to_dataclass(response, MarketDataResponse)

def trades_stream(self) -> Iterable[TradesStreamResponse]:
        request = TradesStreamRequest()
        for response in self.stub.TradesStream(
            request=_grpc_helpers.dataclass_to_protobuff(
                request, operations_pb2.WithdrawLimitsRequest()
            ),
            metadata=self.metadata,
        ):
            yield _grpc_helpers.protobuf_to_dataclass(response, TradesStreamResponse)

В объявлении trades_stream отсутствует request_iterator

Если так и задумано, то подскажите пожалуйста как реализовать функцию trades_stream().

Спасибо!

### Воспроизведение

dotenv_path = join(dirname(__file__), '../.env')
load_dotenv(dotenv_path)

API_KEY = os.environ.get("API_KEY")

def request_iterator(id):
    yield TradesStreamRequest(accounts=id)
    while True:
        time.sleep(1)

with Client(API_KEY) as client:
    # Получаем список id аккаунтов
    accounts = client.users.get_accounts().accounts
    # Среди полученных акrаунтов ищем брокерские счета
    brokerageAccount = [acc for acc in accounts if acc.type == 1]
    # Получаем их id
    brokerageAccountId = [
        acc.id for acc in brokerageAccount if id]
    for orderData in client.orders_stream.trades_stream(request_iterator(brokerageAccountId)):
        print(orderData)

### Tinkoff Invest Version

0.2.0-beta23

### Python Version

3.10

### OS

Windows

### Логи

```shell
Traceback (most recent call last):
  File "*", line 31, in <module>
    for orderData in client.orders_stream.trades_stream(request_iterator(brokerageAccountId)):
  File "*\Roaming\Python\Python310\site-packages\tinkoff\invest\_errors.py", line 43, in wrapper
    yield from func(*args, **kwargs)
TypeError: OrdersStreamService.trades_stream() takes 1 positional argument but 2 were given
```

**Comment by irusland** [comment]
фикс https://github.com/Tinkoff/invest-python/pull/56

После фикса работающим кодом будет:
```python
import os

from tinkoff.invest import AccountType, Client

INVEST_TOKEN = os.environ["INVEST_TOKEN"]


with Client(INVEST_TOKEN) as client:
    # Получаем список id аккаунтов
    accounts = client.users.get_accounts().accounts
    # Среди полученных акrаунтов ищем брокерские счета
    brokerageAccount = [
        acc for acc in accounts if acc.type == AccountType.ACCOUNT_TYPE_TINKOFF
    ]
    # Получаем их id
    brokerageAccountId = [acc.id for acc in brokerageAccount if id]
    for orderData in client.orders_stream.trades_stream(accounts=brokerageAccountId):
        print(orderData)

```

**Comment by HappyManRus** [comment]
В примере пропущен счет IIS. Для кого это важно, поменяйте условие:
`(acc.type == AccountType.ACCOUNT_TYPE_TINKOFF) or (acc.type == AccountType.ACCOUNT_TYPE_TINKOFF_IIS)`
