### ISSUE TITLE
[Feature] Получение типа актива из get_positions()

### ISSUE THREAD

**Issue by bugagashkovich** [Tinkoff/invest-python#61]
### Описание

Функция возвращает PositionsSecurities, без указания типа актива.
Методы share_by, etf_by и т.д. вернут ошибку при попытке поиска по figi тех инструментов, которые не подходят под соответствующие методы.

### Желаемое решение

Добавьте пожалуйста в ответ сервера тип актива, чтобы избавиться от лишних ошибок.

### Дополнительно

PositionsSecurities(figi=string, blocked=int, balance=int, type=enum)

**Comment by daxartio** [comment]
@AlexanderVolkovTCS fyi
Можешь сказать по статусу? Что делаем с issue?

**Comment by AlexanderVolkovTCS** [comment]
1) в api в PositionsSecurities добавим тип инструмента
2) для общего решения предлагаю реализовать https://github.com/Tinkoff/invest-python/issues/79

**Comment by AlexanderVolkovTCS** [comment]
В PositionsSecurities появился instrument_type
