### ISSUE TITLE
Как получить данные по базовому активу для фьючерса?

### ISSUE THREAD

**Issue by Maxim-Fil** [Tinkoff/invest-python#70]
### Что случилось?

Добрый день!
В текущей версии АПИ не понятна связка фьючерсов с базовым инструментом.
В параметрах фьючерса указан тикер базового актива, но чтобы теперь получить по нему данные, одного тикера недостаточно - для получения figi и, соответственно, в дальнейшем данных по базовому активу, требуется еще class_code для базового инструмента. Подскажите, где его взять на фьючерсе?

### Tinkoff Invest Version

0.2.0-beta27

### Python Version

3.8

### OS

Linux

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока рекомендуем либо получить все инструменты и по ним найти нужный тикер, либо использовать https://tinkoff.github.io/investAPI/instruments/#findinstrument. В скором времени будет выгружаться дополнительный параметр - уникальный идентификатор базового актива.
