### ISSUE TITLE
MarketDataStream подписка на одном стриме для всех инструментов или...

### ISSUE THREAD

**Issue by covarex** [Tinkoff/invest-python#78]
### Что случилось?

Здравствуйте!
Такой вопрос, могу ли я подписаться на одном стриме для нескольких инструментов торговли, или же это нужно делать: один стрим - один иструмент?

### Tinkoff Invest Version

Другая

### Python Version

3.10

### OS

Linux

**Comment by daxartio** [comment]
Вариант выше как раз рабочий
