### ISSUE TITLE
Добавить кэш всех инструментов, инициализируемый при старте приложения

### ISSUE THREAD

**Issue by AlexanderVolkovTCS** [Tinkoff/invest-python#79]
### Описание

Есть проблемы:
- зная только figi инструмента, мы не можем без дополнительных вызовов api понять, что это за инструмент
- большое количество клиентов, реализуют свои решения без кеша.

### Желаемое решение

1) Добавить в конфиг параметр - "работать с кэшем в сервисе инструментов" + время жизни этого кэша
2) При старте приложения при включенном параметре загружать все результаты вызовов Shares(), Bonds(), Futures(), ETFs(), Currrencies() в кэш со временем жизни, указываемом в конфиге.

При последующем запросе любого метода Get, GetBy и FindInstrument сервиса инструментов отдавать результаты из кэша.

**Comment by irusland** [comment]
https://github.com/Tinkoff/invest-python/pull/92
