### ISSUE TITLE
PostOrder

### ISSUE THREAD

**Issue by WhyBullyMe** [Tinkoff/invest-python#85]
### PostOrder

При выставлении лимитного торгового поручения необходимо записать Price в Quotation, который состоит из PriceUnits и PriceNano, которые в формате int32-64. Как записать PriceNano в int, если вначале необходимо добавить нули, которые есть только в формате str?

### Tinkoff Invest Version

Другая

### Python Version

Другая

### OS

Windows

**Comment by irusland** [comment]
Обратите внимание на 2 полезных метода конвертации в/из Quotation, возможно, они решат вашу проблему

https://github.com/Tinkoff/invest-python/blob/main/tinkoff/invest/utils.py#L36

https://github.com/Tinkoff/invest-python/blob/main/tinkoff/invest/utils.py#L41
