### ISSUE TITLE
Отсутствие в классе Operation наименования ценных бумаг

### ISSUE THREAD

**Issue by PaaavelZ** [Tinkoff/invest-python#93]
### Что случилось?

Я разрабатываю простого бота, который бы круглосуточно мониторил состояние ценных бумаг в моём портфеле и генерировал отчёт примерно в таком формате: "доходность, количество акций, стоимость бумаг, наименование бумаг (тикер, имя компании или любое другое название, позволяющее идентифицировать актив простому человеку)". Данные я получаю через OperationsService::GetOperations, по их figi'ам получаю текущий курс бумаг и анализирую уже доходность. Однако в классе Operation (https://tinkoff.github.io/investAPI/operations/#operation) отсутствует поле с наименованием этих бумаг, есть лишь figi. И всё бы ничего, да вот только во всём API я не нашёл функции, переводящей figi в какой-нибудь более-менее человеко-понятный вид, а подключать сторонние API - кажется, что-то идёт уже не так. Примечательно, что в классе BrokerReport (https://tinkoff.github.io/investAPI/operations/#brokerreport) есть и name, и ticker - значит, как-то программно это можно реализовать. Хочется узнать, либо что я делаю не так, либо почему такое(-ие) поле(-я) отсутствуют в классе Operation.

### Tinkoff Invest Version

0.2.0-beta30

### Python Version

3.10

### OS

Windows

**Comment by irusland** [comment]
Если я правильно понял, то хочется по figi находить инструмент.

Рассмотрите следующий код:

```python
import os
from pprint import pprint

from tinkoff.invest import Client, InstrumentIdType

TOKEN = os.environ["INVEST_TOKEN"]


def main():
    with Client(TOKEN) as client:
        # получили figi из операций
        figi = "BBG00P35VS94"

        short_info, = client.instruments.find_instrument(query=figi).instruments
        print('Short instrument info')
        pprint(short_info)

        full_info = client.instruments.etf_by(
            id_type=InstrumentIdType.INSTRUMENT_ID_TYPE_FIGI,
            class_code=short_info.class_code,
            id=short_info.figi,
        )
        print('Full instrument info')
        pprint(full_info.instrument)


if __name__ == "__main__":
    main()
```

Он выдаст нужный вам инструмент, в моем примере - ETF
