### ISSUE TITLE
[Bug] Неверное значение цены при запросе market_data.get_last_prices

### ISSUE THREAD

**Issue by Nikolailavr** [Tinkoff/invest-python#97]
### Что случилось?

При запросе цены актива выдается неверное значение после запятой, например цена актива 1.08 в ответе приходит units=1, nano=8000000

### Tinkoff Invest Version

0.2.0-beta32

### Python Version

3.10

### OS

Windows

**Comment by Nikolailavr** [comment]
[LastPrice(figi='BBG000BCTLF6', price=Quotation(units=33, nano=70000000), time=datetime.datetime(2022, 7, 27, 14, 7, 32, 506431, tzinfo=datetime.timezone.utc))]

Реальная цена актива 33.07

**Comment by StEvgeny** [comment]
Дополню, например акция AAPL на 15 минутном интервале, Low больше High:

HistoricCandle(open=Quotation(units=160, nano=760000000), high=Quotation(units=160, nano=760000000), low=Quotation(units=160, nano=80000000), close=Quotation(units=160, nano=80000000), volume=4, time=datetime.datetime(2022, 7, 30, 15, 15, tzinfo=datetime.timezone.utc), is_complete=True) 

А тут например так:

HistoricCandle(open=Quotation(units=165, nano=800000000), high=Quotation(units=165, nano=800000000), low=Quotation(units=165, nano=680000000), close=Quotation(units=165, nano=680000000), volume=193, time=datetime.datetime(2022, 8, 3, 22, 30, tzinfo=datetime.timezone.utc), is_complete=True)

**Comment by daxartio** [comment]
Мне кажется это лучше написать в основной репозиторий. Так как тут нет проблем с самим sdk

**Comment by AlexanderVolkovTCS** [comment]
>Дополню, например акция AAPL на 15 минутном интервале, Low больше High:
HistoricCandle(open=Quotation(units=160, nano=760000000), high=Quotation(units=160, nano=760000000), low=Quotation(units=160, nano=80000000), close=Quotation(units=160, nano=80000000), volume=4, time=datetime.datetime(2022, 7, 30, 15, 15, tzinfo=datetime.timezone.utc), is_complete=True)

Проблемы нет:
high=Quotation(units=160, nano=760**000000**) = 160,76
low=Quotation(units=160, nano=80**000000**) = 160,08

**Comment by AlexanderVolkovTCS** [comment]
>[LastPrice(figi='BBG000BCTLF6', price=Quotation(units=33, nano=70000000), time=datetime.datetime(2022, 7, 27, 14, 7, 32, 506431, tzinfo=datetime.timezone.utc))]
Реальная цена актива 33.07

Тут тоже все верно. См описание форматов: https://tinkoff.github.io/investAPI/faq_custom_types/#moneyvalue
